zuul:
  prefix: /api
  routes:
    backend-hello-server:
      path: /server/**
      url: http://localhost:8071
backend-client-server:
  path: /client/**
  url: http://localhost:8072

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost

    hystrix:
      command:
        default:
          execution:
            isolation:
              thread:
                timeoutInMilliseconds: 60000
    prefer-ip-address: true
